#!/bin/bash

# first compile subproject
script/compile-subproject

# compile main project
./gradlew :app:clean
./gradlew :app:wasmJsBrowserDistribution

rm -rf app/build/release/
mkdir app/build/release/
cp -r app/build/dist/wasmJs/productionExecutable/* app/build/release/
open app/build/release/
